### ISSUE TITLE
Null pointer while making cache only request

### ISSUE THREAD

**Issue by nikkulshrestha** [rohitnareshsharma/easyvolley#1]
The stack trace is as below

 java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at com.android.volley.Request.compareTo(Request.java:686)
        at com.android.volley.Request.compareTo(Request.java:37)
        at java.util.concurrent.PriorityBlockingQueue.siftUpComparable(PriorityBlockingQueue.java:360)
        at java.util.concurrent.PriorityBlockingQueue.offer(PriorityBlockingQueue.java:488)
        at java.util.concurrent.PriorityBlockingQueue.add(PriorityBlockingQueue.java:462)
        at com.easyvolley.NetworkClient.addCacheOnlyRequest(NetworkClient.java:232)
        at com.easyvolley.NetworkRequestBuilder.add(NetworkRequestBuilder.java:249)
        at com.easyvolley.NetworkRequestBuilder.execute(NetworkRequestBuilder.java:282)
        at com.paytmmall.common.weex.WeexBundleUtils.getCachedBundleData(WeexBundleUtils.java:72)
        at com.paytmmall.common.weex.WeexBaseFragment.loadPage(WeexBaseFragment.java:191)
        at com.paytmmall.common.weex.WeexBaseFragment$5.onReceive(WeexBaseFragment.java:530)
        at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:311)
        at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:47)
        at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:120)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2018-11-06 12:45:09.733 15939-16389/? E/GzipInterceptor: Not in GZIP format

**Comment by rohitnareshsharma** [comment]
This is fixed with 0.1.8 version of easyvolley
